/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
    uint32_t *pRccCrReg   = (uint32_t*)0x40023800;
    uint32_t *pRccCfgrReg = (uint32_t*)0x40023808;

    // 1. Bật HSE
    *pRccCrReg |= (1 << 16);

    // 2. Chờ ổn định
    while(!(*pRccCrReg & (1 << 17)));

    // 3. Chọn HSE làm system clock
    *pRccCfgrReg |= (1 << 0);

    // 4. MCO1 = HSE
    *pRccCfgrReg |= (1 << 22);

    // 5. Prescaler /4
    *pRccCfgrReg |= (1 << 25);
    *pRccCfgrReg |= (1 << 26);

    // 6. Enable GPIOA
    uint32_t *pRccAhb1Enr = (uint32_t*)(0x40023800 + 0x30);
    *pRccAhb1Enr |= (1 << 0);

    // 7. PA8 = AF mode
    uint32_t *pGPIOAModeReg = (uint32_t*)0x40020000;
    *pGPIOAModeReg &= ~(0x3 << 16);
    *pGPIOAModeReg |=  (0x2 << 16);

    // 8. AF0
    uint32_t *pGPIOAAltFunHighReg = (uint32_t*)(0x40020000 + 0x24);
    *pGPIOAAltFunHighReg &= ~(0xF << 0);

    while(1);
}
